[project]
name = "convx"
type = "javascript"

[build]
command = "npm run build"
directory = "dist"

[site]
bucket = "./dist"
entry-point = "workers-site"

[env.production]
account_id = "<YOUR_ACCOUNT_ID>"
zone_id = "<YOUR_ZONE_ID>"
route = "convx.yourdomain.com/*"
